# Generated by Django 2.2 on 2019-08-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts_app', '0002_auto_20190819_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
