# Generated by Django 2.2 on 2019-08-21 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts_app', '0003_auto_20190819_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Rate'),
        ),
    ]
