# Generated by Django 2.2 on 2019-08-21 01:09

from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('carts_app', '0004_auto_20190821_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[products.validators.validate_nonzero]),
        ),
    ]
