# Generated by Django 2.2 on 2019-08-21 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts_app', '0006_auto_20190821_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carts_app.Cart'),
            preserve_default=False,
        ),
    ]
