# Generated by Django 2.2 on 2019-08-29 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=100.0, max_digits=7)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('txn_id', models.CharField(default=orders.models.txn_id_generator, max_length=32)),
                ('delivery_expected', models.DateTimeField(blank=True, null=True)),
                ('bill', models.FileField(blank=True, null=True, upload_to='orders/bills/')),
                ('line_1', models.CharField(blank=True, max_length=264)),
                ('line_2', models.CharField(blank=True, max_length=264)),
                ('locality', models.CharField(blank=True, max_length=64)),
                ('zip_code', models.CharField(blank=True, max_length=6)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PL', 'Order Placed'), ('RC', 'Received'), ('PK', 'Packing'), ('SH', 'Shipped'), ('CN', 'Cancelled')], default='PL', max_length=2)),
                ('is_payed', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(blank=True, to='carts_app.CartItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
