# Generated by Django 2.2 on 2019-08-24 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=100.0, max_digits=7)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('order_id', models.CharField(max_length=32)),
                ('delivery_expected', models.DateTimeField(blank=True, null=True)),
                ('bill', models.FileField(blank=True, null=True, upload_to='orders/bills/')),
                ('line_1', models.CharField(blank=True, max_length=264)),
                ('line_2', models.CharField(blank=True, max_length=264)),
                ('locality', models.CharField(blank=True, max_length=64)),
                ('zip_code', models.CharField(blank=True, max_length=6)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PL', 'Order Placed'), ('RC', 'Received'), ('PK', 'Packing'), ('SH', 'Shipped'), ('CN', 'Cancelled')], default='PL', max_length=2)),
                ('is_payed', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(blank=True, null=True, to='carts_app.CartItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=264)),
                ('line_2', models.CharField(max_length=264)),
                ('locality', models.CharField(max_length=64)),
                ('city', models.CharField(default='Pune', max_length=64)),
                ('state', models.CharField(default='Maharashtra', max_length=64)),
                ('zip_code', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=13)),
                ('address_type', models.CharField(choices=[('SH', 'Shop or Office'), ('HM', 'Home')], max_length=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
