# Generated by Django 2.2 on 2019-08-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NP', 'Payment Pending'), ('PL', 'Order Placed'), ('RC', 'Received'), ('PK', 'Packing'), ('SH', 'Shipped'), ('CN', 'Cancelled')], default='NP', max_length=2),
        ),
    ]
