# Generated by Django 2.2 on 2019-08-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts_app', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_product',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='carts_app.CartItem'),
        ),
    ]
