# Generated by Django 2.2 on 2019-08-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190830_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='placed_sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
