# Generated by Django 2.2 on 2019-08-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190830_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NP', 'Payment Pending'), ('PL', 'Order Placed'), ('RS', 'Ready To Ship'), ('SH', 'Shipped'), ('CN', 'Cancelled')], default='NP', max_length=2),
        ),
    ]
