# Generated by Django 2.2 on 2019-09-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190831_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rs_sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
