# Generated by Django 2.2 on 2019-09-01 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_rs_sms_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.FileField(blank=True, null=True, upload_to='orders/bills/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
