# Generated by Django 2.2 on 2019-08-17 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='product',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='specification_name',
        ),
        migrations.RemoveField(
            model_name='specificationname',
            name='category',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
        migrations.DeleteModel(
            name='SpecificationName',
        ),
    ]
