# Generated by Django 2.2 on 2019-09-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, height_field=200, help_text='Ratio should be 3:2 with 600 X 400 px (maximum)', null=True, upload_to='products/categories/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(help_text='Ratio should be 3:2 with 600 X 400 px (maximum)', upload_to='products/photos/'),
        ),
    ]
