# Generated by Django 2.2 on 2019-09-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190901_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, help_text='Ratio should be 3:2 with 600 X 400 px (maximum)', null=True, upload_to='products/categories/'),
        ),
    ]
