# Generated by Django 2.2 on 2019-08-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190817_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='specification_name',
        ),
        migrations.DeleteModel(
            name='SpecificationName',
        ),
    ]
