# Generated by Django 2.2 on 2019-08-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190817_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='per_piece_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=7),
            preserve_default=False,
        ),
    ]
