# Generated by Django 2.2 on 2019-08-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rate_per_piece_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='per_piece_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
